language: minimal

# Our docker image does the cloning
git:
  clone: false

services:
  - docker

before_install:
  - docker pull andyholmes/gsconnect-tests

script:
  - docker run -it andyholmes/gsconnect-tests /gsconnect-tests.sh
  
