project_identifier: org.gnome.Shell.Extensions.GSConnect
files:
  - source: /po/org.gnome.Shell.Extensions.GSConnect.pot
    translation: /po/%two_letters_code%.po
    languages_mapping:
      locale:
        sr-CS: sr@latin
        fr: fr
        de: de
        pt-BR: pt_BR
        nl: nl_NL
        nl-BE: nl_BE
