# GSConect Tests

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - name: Pull test runner
        run: docker pull andyholmes/gsconnect-tests

      # Runs a set of commands using the runners shell
      - name: Run all tests
        env:
          TEST_REPO: ${{ github.event.pull_request.head.repo.clone_url }}
          TEST_BRANCH: ${{ github.event.pull_request.head.ref }}
        run: |
          docker run --env TEST_REPO=$TEST_REPO \
                     --env TEST_BRANCH=$TEST_BRANCH \
                     andyholmes/gsconnect-tests
